server:
  port: 8080

spring:
  application:
    name: SISAGI1

  datasource:
    url: jdbc:mysql://mysql-1b44538e-teste12-0c75.i.aivencloud.com:14216/defaultdb
    username: avnadmin
    password: 'AVNS__RS-lEfprwwV5_AS8Bz'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:

      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true