server:
  port: 8080

spring:
  application:
    name: sisagi

  datasource:
    url: jdbc:mysql://mysql-1b44538e-teste12-0c75.i.aivencloud.com:14216/defaultdb
    username: avnadmin
    password: 'AVNS__RS-lEfprwwV5_AS8Bz'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:

      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs # URL para o JSON da especificação OpenAPI
  swagger-ui:
    path: /swagger-ui.html # URL para a interface do Swagger
  info:
    title: SisAgi - API de Gerenciamento Bancário
    description: "API RESTful para o sistema SisAgi, com operações para clientes, gerentes, contas e transações."
    version: v0.0.1

mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  username: 00d3457a43d624
  password: '84220ba943fdf4'
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true